defaults:
  - _train
  - _self_
  - dataset: motor 

model_cfg:
  operator:
    _target_: multiscale_operator.operators.gnn_perceiver.GraphPeceiverOperator
    d_latents: 128
    d_model: 64
  mlp_hidden_dims: 64
  output_channels: 1
  mlp_decoder: true

data_transform:
  _target_: multiscale_operator.transforms.chain_transforms.ChainedTransforms
  transforms:
    - _target_: multiscale_operator.transforms.normalisation_transform.NormaliseTransform
      mean: ${dataset.statistics.mean}
      std: ${dataset.statistics.std}
    - _target_: multiscale_operator.transforms.absolute_position.AbsolutePositionTransform

train_cfg:
  batch_size: 2
  accumulate_grad_batches: 8

wandb:
  group: final_perceiver_gnn_${dataset.name}
  tags: [perceivergnn, final, '${dataset.name}']

plot_every_n_batches: 24  # = 3*16
mlp_hidden_layer: 3
num_message_passing: 5